version = 0.1

[default.deploy.parameters]
stack_name = "foodmind-ai"
resolve_s3 = true
s3_prefix = "foodmind-ai"
profile = "foodmind-admin"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
